insert into person (id, name, date_of_birth, gender, weight, active) values (nextval('hibernate_sequence'), 'Sean Bowman', DATE '1973-12-06', 'MALE', 105, true);
insert into person (id, name, date_of_birth, gender, weight, active) values (nextval('hibernate_sequence'), 'Alice Nichols', null, 'FEMALE', 74, false);
insert into person (id, name, date_of_birth, gender, weight, active) values (nextval('hibernate_sequence'), 'Norma Hudson', null, 'FEMALE', 58, true);
insert into person (id, name, date_of_birth, gender, weight, active) values (nextval('hibernate_sequence'), 'Shirley Boyd', DATE '1980-10-06', 'FEMALE', null, false);
insert into person (id, name, date_of_birth, gender, weight, active) values (nextval('hibernate_sequence'), 'John Reyes', DATE '1998-03-26', 'MALE', null, true);
insert into person (id, name, date_of_birth, gender, weight, active) values (nextval('hibernate_sequence'), 'Lisa Rodriguez', DATE '1985-02-22', 'FEMALE', null, true);
insert into person (id, name, date_of_birth, gender, weight, active) values (nextval('hibernate_sequence'), 'Gerald Martin', DATE '2016-08-30', 'MALE', 89, true);
insert into person (id, name, date_of_birth, gender, weight, active) values (nextval('hibernate_sequence'), 'Ernest Gardner', DATE '1967-03-16', 'MALE', 101, false);
insert into person (id, name, date_of_birth, gender, weight, active) values (nextval('hibernate_sequence'), 'Harold Black', DATE '1994-02-01', 'MALE', 112, false);
insert into person (id, name, date_of_birth, gender, weight, active) values (nextval('hibernate_sequence'), 'Amanda Grant', DATE '2015-07-14', 'FEMALE', null, false);
insert into person (id, name, date_of_birth, gender, weight, active) values (nextval('hibernate_sequence'), 'Chris Knight', DATE '2012-02-02', 'MALE', 43, false);
insert into person (id, name, date_of_birth, gender, weight, active) values (nextval('hibernate_sequence'), 'Virginia Frazier', DATE '1951-05-31', 'FEMALE', null, false);
insert into person (id, name, date_of_birth, gender, weight, active) values (nextval('hibernate_sequence'), 'Johnny Cooper', null, 'MALE', 54, true);
insert into person (id, name, date_of_birth, gender, weight, active) values (nextval('hibernate_sequence'), 'Kevin Rogers', DATE '1966-07-12', 'MALE', 58, true);
insert into person (id, name, date_of_birth, gender, weight, active) values (nextval('hibernate_sequence'), 'Jeremy Dunn', DATE '1950-07-25', 'MALE', 58, true);
insert into person (id, name, date_of_birth, gender, weight, active) values (nextval('hibernate_sequence'), 'Margaret Adams', DATE '1980-04-14', 'FEMALE', 41, false);
insert into person (id, name, date_of_birth, gender, weight, active) values (nextval('hibernate_sequence'), 'Susan Smith', DATE '2007-09-22', 'FEMALE', null, true);
insert into person (id, name, date_of_birth, gender, weight, active) values (nextval('hibernate_sequence'), 'Eugene Lane', null, 'MALE', 46, false);
insert into person (id, name, date_of_birth, gender, weight, active) values (nextval('hibernate_sequence'), 'Katherine Cox', DATE '1991-12-28', 'FEMALE', null, false);
insert into person (id, name, date_of_birth, gender, weight, active) values (nextval('hibernate_sequence'), 'Jeremy Harvey', DATE '1979-07-24', 'MALE', 107, false);
insert into person (id, name, date_of_birth, gender, weight, active) values (nextval('hibernate_sequence'), 'Victor Burke', DATE '1990-06-08', 'MALE', null, false);
insert into person (id, name, date_of_birth, gender, weight, active) values (nextval('hibernate_sequence'), 'Fred Howard', DATE '1973-03-12', 'MALE', 117, true);
insert into person (id, name, date_of_birth, gender, weight, active) values (nextval('hibernate_sequence'), 'Jesse Cole', DATE '1980-05-29', 'MALE', 53, true);
insert into person (id, name, date_of_birth, gender, weight, active) values (nextval('hibernate_sequence'), 'Antonio Stone', DATE '1951-07-22', 'MALE', null, false);
insert into person (id, name, date_of_birth, gender, weight, active) values (nextval('hibernate_sequence'), 'Marilyn Stewart', DATE '1998-12-21', 'FEMALE', 105, false);
insert into person (id, name, date_of_birth, gender, weight, active) values (nextval('hibernate_sequence'), 'Gregory Hunter', null, 'MALE', 76, false);
insert into person (id, name, date_of_birth, gender, weight, active) values (nextval('hibernate_sequence'), 'Steve Torres', DATE '1990-08-22', 'MALE', null, false);
insert into person (id, name, date_of_birth, gender, weight, active) values (nextval('hibernate_sequence'), 'Elizabeth Hart', DATE '1966-03-22', 'FEMALE', 55, true);
insert into person (id, name, date_of_birth, gender, weight, active) values (nextval('hibernate_sequence'), 'Jason Fuller', DATE '2004-01-09', 'MALE', 52, true);
insert into person (id, name, date_of_birth, gender, weight, active) values (nextval('hibernate_sequence'), 'Sarah Fowler', DATE '2001-12-12', 'FEMALE', null, false);
insert into person (id, name, date_of_birth, gender, weight, active) values (nextval('hibernate_sequence'), 'Wanda Dixon', DATE '1998-09-26', 'FEMALE', 66, false);
insert into person (id, name, date_of_birth, gender, weight, active) values (nextval('hibernate_sequence'), 'Joyce Franklin', DATE '1965-01-31', 'FEMALE', null, false);
insert into person (id, name, date_of_birth, gender, weight, active) values (nextval('hibernate_sequence'), 'Roy Harris', DATE '1975-03-30', 'MALE', 110, true);
insert into person (id, name, date_of_birth, gender, weight, active) values (nextval('hibernate_sequence'), 'Kevin Nelson', null, 'MALE', 49, false);
insert into person (id, name, date_of_birth, gender, weight, active) values (nextval('hibernate_sequence'), 'Judy Larson', DATE '2012-08-08', 'FEMALE', null, true);
insert into person (id, name, date_of_birth, gender, weight, active) values (nextval('hibernate_sequence'), 'Antonio Fuller', DATE '1956-05-06', 'MALE', null, true);
insert into person (id, name, date_of_birth, gender, weight, active) values (nextval('hibernate_sequence'), 'John Fox', null, 'MALE', 103, false);
insert into person (id, name, date_of_birth, gender, weight, active) values (nextval('hibernate_sequence'), 'Julie Dean', DATE '1989-07-16', 'FEMALE', null, true);
insert into person (id, name, date_of_birth, gender, weight, active) values (nextval('hibernate_sequence'), 'Michael Hernandez', null, 'MALE', 53, false);
insert into person (id, name, date_of_birth, gender, weight, active) values (nextval('hibernate_sequence'), 'Harry Graham', DATE '2016-06-07', 'MALE', 116, false);
insert into person (id, name, date_of_birth, gender, weight, active) values (nextval('hibernate_sequence'), 'Susan Perry', DATE '1986-06-02', 'FEMALE', null, false);
insert into person (id, name, date_of_birth, gender, weight, active) values (nextval('hibernate_sequence'), 'Steven Nelson', DATE '1955-03-03', 'MALE', 80, true);
insert into person (id, name, date_of_birth, gender, weight, active) values (nextval('hibernate_sequence'), 'Evelyn Long', DATE '1976-12-31', 'FEMALE', 81, true);
insert into person (id, name, date_of_birth, gender, weight, active) values (nextval('hibernate_sequence'), 'Kelly Hamilton', DATE '1994-04-20', 'FEMALE', 57, true);
insert into person (id, name, date_of_birth, gender, weight, active) values (nextval('hibernate_sequence'), 'Richard Smith', DATE '2004-09-25', 'MALE', null, false);
insert into person (id, name, date_of_birth, gender, weight, active) values (nextval('hibernate_sequence'), 'Paula Walker', DATE '1988-01-24', 'FEMALE', null, false);
insert into person (id, name, date_of_birth, gender, weight, active) values (nextval('hibernate_sequence'), 'Melissa Reid', DATE '1986-06-15', 'FEMALE', 55, false);
insert into person (id, name, date_of_birth, gender, weight, active) values (nextval('hibernate_sequence'), 'Michelle Adams', DATE '1976-06-01', 'FEMALE', 52, false);
insert into person (id, name, date_of_birth, gender, weight, active) values (nextval('hibernate_sequence'), 'Marilyn Boyd', DATE '2007-10-12', 'FEMALE', 94, true);
insert into person (id, name, date_of_birth, gender, weight, active) values (nextval('hibernate_sequence'), 'Daniel King', DATE '1979-04-12', 'MALE', 61, true);
insert into person (id, name, date_of_birth, gender, weight, active) values (nextval('hibernate_sequence'), 'Mark Reed', DATE '1975-04-20', 'MALE', null, false);
insert into person (id, name, date_of_birth, gender, weight, active) values (nextval('hibernate_sequence'), 'Stephanie Kelley', DATE '1967-06-21', 'FEMALE', 111, false);
insert into person (id, name, date_of_birth, gender, weight, active) values (nextval('hibernate_sequence'), 'Evelyn Burke', DATE '1955-07-01', 'FEMALE', null, true);
insert into person (id, name, date_of_birth, gender, weight, active) values (nextval('hibernate_sequence'), 'Lori Price', DATE '1956-08-28', 'FEMALE', null, false);
insert into person (id, name, date_of_birth, gender, weight, active) values (nextval('hibernate_sequence'), 'Barbara Frazier', DATE '2008-12-24', 'FEMALE', null, false);
insert into person (id, name, date_of_birth, gender, weight, active) values (nextval('hibernate_sequence'), 'Patricia Cunningham', DATE '1954-09-08', 'FEMALE', null, true);
insert into person (id, name, date_of_birth, gender, weight, active) values (nextval('hibernate_sequence'), 'Jane Alexander', DATE '1998-11-02', 'FEMALE', 91, false);
insert into person (id, name, date_of_birth, gender, weight, active) values (nextval('hibernate_sequence'), 'Justin Jackson', DATE '1979-02-05', 'MALE', 73, true);
insert into person (id, name, date_of_birth, gender, weight, active) values (nextval('hibernate_sequence'), 'Donald Welch', DATE '1984-04-05', 'MALE', 99, true);
insert into person (id, name, date_of_birth, gender, weight, active) values (nextval('hibernate_sequence'), 'Jerry Carroll', DATE '2016-02-19', 'MALE', null, true);
insert into person (id, name, date_of_birth, gender, weight, active) values (nextval('hibernate_sequence'), 'Rebecca Lee', DATE '1981-09-11', 'FEMALE', 90, false);
insert into person (id, name, date_of_birth, gender, weight, active) values (nextval('hibernate_sequence'), 'Anna Powell', DATE '2005-01-27', 'FEMALE', 92, false);
insert into person (id, name, date_of_birth, gender, weight, active) values (nextval('hibernate_sequence'), 'Gary Lawrence', DATE '1952-06-22', 'MALE', 105, false);
insert into person (id, name, date_of_birth, gender, weight, active) values (nextval('hibernate_sequence'), 'Victor Ramirez', DATE '1991-03-31', 'MALE', null, true);
insert into person (id, name, date_of_birth, gender, weight, active) values (nextval('hibernate_sequence'), 'Wayne Ryan', DATE '1959-05-12', 'MALE', 85, false);
insert into person (id, name, date_of_birth, gender, weight, active) values (nextval('hibernate_sequence'), 'Ann Owens', DATE '1994-03-15', 'FEMALE', 108, true);
insert into person (id, name, date_of_birth, gender, weight, active) values (nextval('hibernate_sequence'), 'Raymond Payne', DATE '1951-04-15', 'MALE', 72, true);
insert into person (id, name, date_of_birth, gender, weight, active) values (nextval('hibernate_sequence'), 'Julia Graham', DATE '1965-07-29', 'FEMALE', 51, false);
insert into person (id, name, date_of_birth, gender, weight, active) values (nextval('hibernate_sequence'), 'Stephanie Robertson', DATE '1977-03-24', 'FEMALE', 97, false);
insert into person (id, name, date_of_birth, gender, weight, active) values (nextval('hibernate_sequence'), 'Eugene Lynch', DATE '1956-03-05', 'MALE', null, false);
insert into person (id, name, date_of_birth, gender, weight, active) values (nextval('hibernate_sequence'), 'Wanda Russell', DATE '1975-11-02', 'FEMALE', 72, false);
insert into person (id, name, date_of_birth, gender, weight, active) values (nextval('hibernate_sequence'), 'Paula Dunn', DATE '2010-09-23', 'FEMALE', null, false);
insert into person (id, name, date_of_birth, gender, weight, active) values (nextval('hibernate_sequence'), 'Samuel Torres', DATE '2000-01-15', 'MALE', 120, true);
insert into person (id, name, date_of_birth, gender, weight, active) values (nextval('hibernate_sequence'), 'Carol Smith', DATE '1969-10-29', 'FEMALE', 49, true);
insert into person (id, name, date_of_birth, gender, weight, active) values (nextval('hibernate_sequence'), 'Judy Mendoza', DATE '1972-10-21', 'FEMALE', 43, true);
insert into person (id, name, date_of_birth, gender, weight, active) values (nextval('hibernate_sequence'), 'Eric Garrett', null, 'MALE', 67, true);
insert into person (id, name, date_of_birth, gender, weight, active) values (nextval('hibernate_sequence'), 'Rose Hawkins', DATE '1986-03-03', 'FEMALE', 41, false);
insert into person (id, name, date_of_birth, gender, weight, active) values (nextval('hibernate_sequence'), 'Heather Simmons', DATE '2005-12-14', 'FEMALE', null, true);
insert into person (id, name, date_of_birth, gender, weight, active) values (nextval('hibernate_sequence'), 'Russell Williams', DATE '1969-03-08', 'MALE', 78, false);
insert into person (id, name, date_of_birth, gender, weight, active) values (nextval('hibernate_sequence'), 'Nicholas Day', DATE '2001-02-28', 'MALE', null, true);
insert into person (id, name, date_of_birth, gender, weight, active) values (nextval('hibernate_sequence'), 'Jesse Perez', DATE '1956-02-27', 'MALE', 61, true);
insert into person (id, name, date_of_birth, gender, weight, active) values (nextval('hibernate_sequence'), 'Justin Carter', DATE '1951-10-06', 'MALE', 100, false);
insert into person (id, name, date_of_birth, gender, weight, active) values (nextval('hibernate_sequence'), 'Timothy Reid', DATE '1991-05-12', 'MALE', 58, true);
insert into person (id, name, date_of_birth, gender, weight, active) values (nextval('hibernate_sequence'), 'Robert Reid', DATE '1987-08-02', 'MALE', null, true);
insert into person (id, name, date_of_birth, gender, weight, active) values (nextval('hibernate_sequence'), 'Jean Baker', DATE '2005-08-08', 'FEMALE', 55, false);
insert into person (id, name, date_of_birth, gender, weight, active) values (nextval('hibernate_sequence'), 'Joseph Perkins', DATE '1984-06-22', 'MALE', 116, false);
insert into person (id, name, date_of_birth, gender, weight, active) values (nextval('hibernate_sequence'), 'Maria Reed', DATE '1964-06-11', 'FEMALE', 49, true);
insert into person (id, name, date_of_birth, gender, weight, active) values (nextval('hibernate_sequence'), 'Aaron Harrison', DATE '1951-10-31', 'MALE', 109, false);
insert into person (id, name, date_of_birth, gender, weight, active) values (nextval('hibernate_sequence'), 'Gregory Knight', DATE '1994-11-21', 'MALE', null, true);
insert into person (id, name, date_of_birth, gender, weight, active) values (nextval('hibernate_sequence'), 'Annie Rose', DATE '1989-01-10', 'FEMALE', null, true);
insert into person (id, name, date_of_birth, gender, weight, active) values (nextval('hibernate_sequence'), 'David Lane', DATE '2003-08-23', 'MALE', null, true);
insert into person (id, name, date_of_birth, gender, weight, active) values (nextval('hibernate_sequence'), 'Mary Mcdonald', DATE '1950-06-14', 'FEMALE', null, true);
insert into person (id, name, date_of_birth, gender, weight, active) values (nextval('hibernate_sequence'), 'Judy Hanson', null, 'FEMALE', 60, false);
insert into person (id, name, date_of_birth, gender, weight, active) values (nextval('hibernate_sequence'), 'James Marshall', DATE '1993-09-29', 'MALE', null, true);
insert into person (id, name, date_of_birth, gender, weight, active) values (nextval('hibernate_sequence'), 'Larry Garrett', null, 'MALE', 55, false);
insert into person (id, name, date_of_birth, gender, weight, active) values (nextval('hibernate_sequence'), 'David Russell', DATE '2002-10-18', 'MALE', 45, false);
insert into person (id, name, date_of_birth, gender, weight, active) values (nextval('hibernate_sequence'), 'Rose Greene', DATE '2004-08-12', 'FEMALE', 105, true);
insert into person (id, name, date_of_birth, gender, weight, active) values (nextval('hibernate_sequence'), 'Richard Fisher', null, 'MALE', 100, true);
insert into person (id, name, date_of_birth, gender, weight, active) values (nextval('hibernate_sequence'), 'Sean Hill', DATE '2003-06-29', 'MALE', 51, true);
insert into person (id, name, date_of_birth, gender, weight, active) values (nextval('hibernate_sequence'), 'Sean Bell', DATE '1994-05-08', 'MALE', 56, false);